# Generated by Django 5.1.7 on 2025-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=100)),
                ('payments', models.CharField(max_length=100)),
                ('workexp', models.CharField(max_length=100)),
                ('schedule', models.IntegerField()),
                ('whours', models.IntegerField()),
                ('favorite', models.BooleanField(default=False)),
                ('imageUrl', models.URLField(max_length=255)),
                ('wformat', models.CharField(max_length=100)),
            ],
        ),
    ]
